version: 0.1
phases:
  build:
    commands:
      - chmod 755 gradlew
      - ./gradlew clean war
      - ./gradlew clean integrationTest
      - ls -al
artifacts:
  files:
      - build/**/*
      - awsscripts/install_dependencies.sh
      - awsscripts/start_application.sh
      - awsscripts/stop_application.sh
      - awsscripts/aws_codedeploy_config.sh
      - appspec.yml  
discard-paths: yes
